/** @type {import('tailwindcss').Config} */
// 颜色/字号/圆角 token 全部来自 Stitch 导出的 DESIGN.md，与 PRD §5 视觉风格一致。
// 语义色改由 CSS 变量驱动（style.css 中 :root 与 .dark 分别定义浅/深值），
// 这样切换 .dark 时 bg-surface / text-on-surface 等会自动套用深色值，无需逐处加 dark: 前缀。
const C = (name) => `rgb(var(${name}) / <alpha-value>)`

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{vue,js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        surface: C('--c-surface'),
        'surface-dim': C('--c-surface-dim'),
        'surface-bright': C('--c-surface-bright'),
        'surface-container-lowest': C('--c-surface-container-lowest'),
        'surface-container-low': C('--c-surface-container-low'),
        'surface-container': C('--c-surface-container'),
        'surface-container-high': C('--c-surface-container-high'),
        'surface-container-highest': C('--c-surface-container-highest'),
        'on-surface': C('--c-on-surface'),
        'on-surface-variant': C('--c-on-surface-variant'),
        'inverse-surface': C('--c-inverse-surface'),
        'inverse-on-surface': C('--c-inverse-on-surface'),
        outline: C('--c-outline'),
        'outline-variant': C('--c-outline-variant'),
        'surface-tint': C('--c-surface-tint'),
        primary: C('--c-primary'),
        'on-primary': C('--c-on-primary'),
        'primary-container': C('--c-primary-container'),
        'on-primary-container': C('--c-on-primary-container'),
        'inverse-primary': C('--c-inverse-primary'),
        secondary: C('--c-secondary'),
        'on-secondary': C('--c-on-secondary'),
        'secondary-container': C('--c-secondary-container'),
        'on-secondary-container': C('--c-on-secondary-container'),
        tertiary: C('--c-tertiary'),
        'on-tertiary': C('--c-on-tertiary'),
        'tertiary-container': C('--c-tertiary-container'),
        'on-tertiary-container': C('--c-on-tertiary-container'),
        error: C('--c-error'),
        'on-error': C('--c-on-error'),
        'error-container': C('--c-error-container'),
        'on-error-container': C('--c-on-error-container'),
        'primary-fixed': C('--c-primary-fixed'),
        'primary-fixed-dim': C('--c-primary-fixed-dim'),
        'on-primary-fixed': C('--c-on-primary-fixed'),
        'on-primary-fixed-variant': C('--c-on-primary-fixed-variant'),
        'secondary-fixed': C('--c-secondary-fixed'),
        'secondary-fixed-dim': C('--c-secondary-fixed-dim'),
        'on-secondary-fixed': C('--c-on-secondary-fixed'),
        'on-secondary-fixed-variant': C('--c-on-secondary-fixed-variant'),
        'tertiary-fixed': C('--c-tertiary-fixed'),
        'tertiary-fixed-dim': C('--c-tertiary-fixed-dim'),
        'on-tertiary-fixed': C('--c-on-tertiary-fixed'),
        'on-tertiary-fixed-variant': C('--c-on-tertiary-fixed-variant'),
        background: C('--c-background'),
        'on-background': C('--c-on-background'),
        'surface-variant': C('--c-surface-variant'),
        'bg-page': C('--c-bg-page'),
        'bg-card': C('--c-bg-card'),
        'text-primary': C('--c-text-primary'),
        'text-secondary': C('--c-text-secondary'),
        success: C('--c-success'),
        warning: C('--c-warning'),
        info: C('--c-info'),
        brand: C('--c-brand'),
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1rem',
        '3xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        'unit-4': '4px',
        'unit-8': '8px',
        'unit-16': '16px',
        'unit-24': '24px',
        'card-padding': '1.5rem',
        'sidebar-width': '240px',
        'grid-gutter': '1.5rem',
        'hero-gap': '2rem',
      },
      fontFamily: {
        'headline-lg': ['Inter', 'sans-serif'],
        'headline-lg-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'headline-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-sm': ['Inter', 'sans-serif'],
        'label-sm': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'headline-lg': ['24px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-lg-mobile': ['20px', { lineHeight: '1.3', fontWeight: '600' }],
        'headline-md': ['18px', { lineHeight: '1.4', fontWeight: '600' }],
        'headline-sm': ['15px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.4', letterSpacing: '0.02em', fontWeight: '400' }],
      },
      boxShadow: {
        'fab': '0 8px 24px -4px rgba(108,92,231,0.35)',
        'glass': '0 4px 6px -1px rgba(0,0,0,0.05), 0 2px 4px -1px rgba(0,0,0,0.03)',
        'glass-hover': '0 10px 15px -3px rgba(0,0,0,0.08), 0 4px 6px -2px rgba(0,0,0,0.04)',
      },
    },
  },
  plugins: [],
}
